//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAPE.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAPE.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The target proxy cannot be detected in this environment. You must specify its information explicitly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setup_AuthenticationProxy_Description_NeedToChange {
            get {
                return ResourceManager.GetString("Setup_AuthenticationProxy_Description_NeedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default setting is provided for this environment. Use this settings if possible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setup_Description_DefaultValueProvided {
            get {
                return ResourceManager.GetString("Setup_Description_DefaultValueProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No need to change the current settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setup_Description_NoNeedToChange {
            get {
                return ResourceManager.GetString("Setup_Description_NoNeedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The settings for the proxy server in this environment is configured automatically, by an automatic configuration script for example. In this case MAPE cannot detect the &quot;Bypass proxy server for local addresses&quot; and &quot;Do not use proxy server for addresses beginning with:&quot; settings automatically. You must specify them explicitly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setup_SystemSettingsSwitch_Description_NeedToChange {
            get {
                return ResourceManager.GetString("Setup_SystemSettingsSwitch_Description_NeedToChange", resourceCulture);
            }
        }
    }
}
