//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAPE.Windows.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAPE.Windows.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MAPE
        ///(May Authentication Proxy Explode) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_ApplicationName {
            get {
                return ResourceManager.GetString("AboutWindow_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software uses following components に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_ComponentsGroupBox_Header {
            get {
                return ResourceManager.GetString("AboutWindow_ComponentsGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newtonsoft.Json v9.0.1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_ComponentsList {
            get {
                return ResourceManager.GetString("AboutWindow_ComponentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About MAPE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActualProxySettingsControl_authenticationProxyGroup_Header {
            get {
                return ResourceManager.GetString("ActualProxySettingsControl_authenticationProxyGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Detect Automatically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActualProxySettingsControl_autoDetectProxyCheckBox_Content {
            get {
                return ResourceManager.GetString("ActualProxySettingsControl_autoDetectProxyCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Host Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActualProxySettingsControl_hostNameLabel_Content {
            get {
                return ResourceManager.GetString("ActualProxySettingsControl_hostNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Port: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActualProxySettingsControl_portLabel_Content {
            get {
                return ResourceManager.GetString("ActualProxySettingsControl_portLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAPE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The credential for {0} is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_descriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("CredentialDialog_descriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable &quot;Basic Authentication _Assumption Mode&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_EnableAssumptionModeCheckBox_Content {
            get {
                return ResourceManager.GetString("CredentialDialog_EnableAssumptionModeCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _End Point: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_endPointLabel_Content {
            get {
                return ResourceManager.GetString("CredentialDialog_endPointLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_passwordLabel_Content {
            get {
                return ResourceManager.GetString("CredentialDialog_passwordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save the credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_Persistency_Persistent {
            get {
                return ResourceManager.GetString("CredentialDialog_Persistency_Persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   keep during this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_Persistency_Process {
            get {
                return ResourceManager.GetString("CredentialDialog_Persistency_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   do not save the credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_Persistency_Session {
            get {
                return ResourceManager.GetString("CredentialDialog_Persistency_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How _save the credential? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_persistencyGroup_Header {
            get {
                return ResourceManager.GetString("CredentialDialog_persistencyGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credential Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_Title {
            get {
                return ResourceManager.GetString("CredentialDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _User Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CredentialDialog_userNameLabel_Content {
            get {
                return ResourceManager.GetString("CredentialDialog_userNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListenerDialog_addressLabel_Content {
            get {
                return ResourceManager.GetString("ListenerDialog_addressLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Backlog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListenerDialog_backlogLabel_Content {
            get {
                return ResourceManager.GetString("ListenerDialog_backlogLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListenerDialog_portLabel_Content {
            get {
                return ResourceManager.GetString("ListenerDialog_portLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listener に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListenerDialog_Title {
            get {
                return ResourceManager.GetString("ListenerDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About MAPE ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_aboutMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_aboutMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C_hase the last log in the Log list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_chaseLastLogMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_chaseLastLogMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_clearMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_clearMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_closeMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_closeMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ComponentName_Header {
            get {
                return ResourceManager.GetString("MainWindow_ComponentName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_fileMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_fileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_helpMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_helpMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help Topics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_helptopicMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_helptopicMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_levelLabel_Content {
            get {
                return ResourceManager.GetString("MainWindow_levelLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lo_g に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_logLabel_Content {
            get {
                return ResourceManager.GetString("MainWindow_logLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log _Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_loglevelMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_loglevelMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_logMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_logMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Message_Header {
            get {
                return ResourceManager.GetString("MainWindow_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_proxyMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_proxyMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pro_xy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_proxyToggleButton_Content {
            get {
                return ResourceManager.GetString("MainWindow_proxyToggleButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Settings ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_settingsMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_settingsMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Severity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Severity_Header {
            get {
                return ResourceManager.GetString("MainWindow_Severity_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_startMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_startMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_stopMenu_Header {
            get {
                return ResourceManager.GetString("MainWindow_stopMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Timestamp_Header {
            get {
                return ResourceManager.GetString("MainWindow_Timestamp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon OffIcon {
            get {
                object obj = ResourceManager.GetObject("OffIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon OnIcon {
            get {
                object obj = ResourceManager.GetObject("OnIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   _Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_addButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_addButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_addressColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_addressColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assumption Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_assumptionModeColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_assumptionModeColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backlog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_backlogColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_backlogColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Bypass proxy server for local addresses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_bypassProxyCheckBox_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_bypassProxyCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credentials に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_credentialsTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_credentialsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_downButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_downButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_editButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_editButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Enable System Settings Switcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_enableSystemSettingSwitherCheckBox_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_enableSystemSettingSwitherCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_endPointColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_endPointColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do _not use proxy server for addresses beginning with: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_exclusionLabel_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_exclusionLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The first listener is the MainListener. It is registered to the system as the proxy when the system settings is swithed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_listenerListLabel_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_listenerListLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listeners に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_listenersTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_listenersTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Log Level: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_logLevelLabel_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_logLevelLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a credential for the same proxy &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Message_ConflictingCredential {
            get {
                return ResourceManager.GetString("SettingsWindow_Message_ConflictingCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a listener which has the same end point &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Message_ConflictingListener {
            get {
                return ResourceManager.GetString("SettingsWindow_Message_ConflictingListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an error input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Message_ErrorExists {
            get {
                return ResourceManager.GetString("SettingsWindow_Message_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_miscGroup_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_miscGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_miscTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_miscTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Persistence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_persistenceColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_persistenceColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_portColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_portColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_proxyTab_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_proxyTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_removeButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_removeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rese_t to Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_resetButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_resetButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial _Delay: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_resumeDelay_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_resumeDelay_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resuming proxying at resuming from system sleep/hibernation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_resumeGroup_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_resumeGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry _Interval: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_resumeInterval_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_resumeInterval_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try _Count: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_resumeTryCount_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_resumeTryCount_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Authentication Retry Count: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_retryLabel_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_retryLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save As Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_saveAsDefaultButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_saveAsDefaultButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings during proxying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_switchedSettingsGroup_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_switchedSettingsGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Settings Switcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_systemSettingsSwitherGroup_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_systemSettingsSwitherGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings (Read Only: running proxy now) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Title_ReadOnly {
            get {
                return ResourceManager.GetString("SettingsWindow_Title_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_upButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindow_upButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_userNameColumn_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_userNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_authenticationProxyTabItem_Header {
            get {
                return ResourceManager.GetString("SetupWindow_authenticationProxyTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back(_&lt;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_backButton_Content {
            get {
                return ResourceManager.GetString("SetupWindow_backButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_finishButton_Content {
            get {
                return ResourceManager.GetString("SetupWindow_finishButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can operate MAPE by the context menu of its task tray icon or the menu of its main window.
        ///Select the &quot;Start Proxying&quot; menu to start proxying connections. Select the &quot;Settings&quot; menu to edit its settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_finishingDescriptionTextBox_Text_Addition {
            get {
                return ResourceManager.GetString("SetupWindow_finishingDescriptionTextBox_Text_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finishing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_finishingTabItem_Header {
            get {
                return ResourceManager.GetString("SetupWindow_finishingTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an unacceptable input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_Message_Error {
            get {
                return ResourceManager.GetString("SetupWindow_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current settings are not tested. Do you want to proceed anyway? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_Message_NotTested {
            get {
                return ResourceManager.GetString("SetupWindow_Message_NotTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next(_&gt;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_nextButton_Content {
            get {
                return ResourceManager.GetString("SetupWindow_nextButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Settings Switch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_systemSettingsSwitchTabItem_Header {
            get {
                return ResourceManager.GetString("SetupWindow_systemSettingsSwitchTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target _URL: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_targetUrlLabel_Content {
            get {
                return ResourceManager.GetString("SetupWindow_targetUrlLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_testButton_Content {
            get {
                return ResourceManager.GetString("SetupWindow_testButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_testTabItem_Header {
            get {
                return ResourceManager.GetString("SetupWindow_testTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial Setup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupWindow_Title {
            get {
                return ResourceManager.GetString("SetupWindow_Title", resourceCulture);
            }
        }
    }
}
